---
- name: Find /dev/sda readahead
  command: /sbin/blockdev --getra {{ vertica_block_dev }}
  register: readahead_size
  changed_when: False

- name: Fix /dev/sda readahead
  command: /sbin/blockdev --setra 2048 {{ vertica_block_dev }}
  when: readahead_size.stdout != "2048"

- name: Fix /dev/sda readahead permanently
  lineinfile:
    path: /etc/rc.local
    regexp: '^/sbin/blockdev --setra 2048 {{ vertica_block_dev }}'
    insertbefore: '^exit 0'
    line: '/sbin/blockdev --setra 2048 {{ vertica_block_dev }}'
  when: readahead_size.stdout != "2048"