---
- name: write swap file
  command: fallocate -l 2048 /mnt/swapfile
  args:
    creates: /mnt/swapfile
  register: write_swapfile
  when: ansible_swaptotal_mb < 2048

- name: set swap file permissions
  file:
    path: /mnt/swapfile
    owner: root
    group: root
    mode: 0600
  when: write_swapfile.changed

- name: create swap file
  command: mkswap /mnt/swapfile
  register: _create_swapfile
  when: write_swapfile.changed

- name: Turn swap on
  command: swapon /mnt/swapfile
  when: write_swapfile.changed

- name: add swapfile to /etc/fstab
  mount:
    name: none
    src: /mnt/swapfile
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
  when: write_swapfile.changed

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
    reload: true
    state: present