---
- name: Create swap space
  command: dd if=/dev/zero of=/mnt/swapfile bs=1024 count=2097152
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /mnt/swapfile
  when: ansible_swaptotal_mb < 1

- name: Turn swap on
  command: swapon /mnt/swapfile
  when: ansible_swaptotal_mb < 1

- name: Get swappiness value
  command: cat /proc/sys/vm/swappiness
  register: current_swappiness
  changed_when: False

- name: Set swapiness to 1 (use swap only as the last resort)
  shell: echo 1 > /proc/sys/vm/swappiness
  when: current_swappiness.stdout != '1'